# This file is for building as a Godot module.
def can_build(env, platform):
    return True


def configure(env):
    pass


def get_doc_classes():
    return [
        "VisualShader",
        "VisualShaderNode",
        "VisualShaderNodeCustom",
        "VisualShaderNodeInput",
        "VisualShaderNodeOutput",
        "VisualShaderNodeResizableBase",
        "VisualShaderNodeGroupBase",
        "VisualShaderNodeConstant",
        "VisualShaderNodeVectorBase",
        "VisualShaderNodeComment",
        "VisualShaderNodeFloatConstant",
        "VisualShaderNodeIntConstant",
        "VisualShaderNodeBooleanConstant",
        "VisualShaderNodeColorConstant",
        "VisualShaderNodeVec2Constant",
        "VisualShaderNodeVec3Constant",
        "VisualShaderNodeVec4Constant",
        "VisualShaderNodeTransformConstant",
        "VisualShaderNodeFloatOp",
        "VisualShaderNodeIntOp",
        "VisualShaderNodeVectorOp",
        "VisualShaderNodeColorOp",
        "VisualShaderNodeTransformOp",
        "VisualShaderNodeTransformVecMult",
        "VisualShaderNodeFloatFunc",
        "VisualShaderNodeIntFunc",
        "VisualShaderNodeVectorFunc",
        "VisualShaderNodeColorFunc",
        "VisualShaderNodeTransformFunc",
        "VisualShaderNodeUVFunc",
        "VisualShaderNodeUVPolarCoord",
        "VisualShaderNodeDotProduct",
        "VisualShaderNodeVectorLen",
        "VisualShaderNodeDeterminant",
        "VisualShaderNodeDerivativeFunc",
        "VisualShaderNodeClamp",
        "VisualShaderNodeFaceForward",
        "VisualShaderNodeOuterProduct",
        "VisualShaderNodeSmoothStep",
        "VisualShaderNodeStep",
        "VisualShaderNodeVectorDistance",
        "VisualShaderNodeVectorRefract",
        "VisualShaderNodeMix",
        "VisualShaderNodeVectorCompose",
        "VisualShaderNodeTransformCompose",
        "VisualShaderNodeVectorDecompose",
        "VisualShaderNodeTransformDecompose",
        "VisualShaderNodeTexture",
        "VisualShaderNodeCurveTexture",
        "VisualShaderNodeCurveXYZTexture",
        "VisualShaderNodeSample3D",
        "VisualShaderNodeTexture2DArray",
        "VisualShaderNodeTexture3D",
        "VisualShaderNodeCubemap",
        "VisualShaderNodeParameter",
        "VisualShaderNodeParameterRef",
        "VisualShaderNodeFloatParameter",
        "VisualShaderNodeIntParameter",
        "VisualShaderNodeBooleanParameter",
        "VisualShaderNodeColorParameter",
        "VisualShaderNodeVec2Parameter",
        "VisualShaderNodeVec3Parameter",
        "VisualShaderNodeVec4Parameter",
        "VisualShaderNodeTransformParameter",
        "VisualShaderNodeTextureParameter",
        "VisualShaderNodeTexture2DParameter",
        "VisualShaderNodeTextureParameterTriplanar",
        "VisualShaderNodeTexture2DArrayParameter",
        "VisualShaderNodeTexture3DParameter",
        "VisualShaderNodeCubemapParameter",
        "VisualShaderNodeLinearSceneDepth",
        "VisualShaderNodeIf",
        "VisualShaderNodeSwitch",
        "VisualShaderNodeFresnel",
        "VisualShaderNodeExpression",
        "VisualShaderNodeGlobalExpression",
        "VisualShaderNodeIs",
        "VisualShaderNodeCompare",
        "VisualShaderNodeMultiplyAdd",
        "VisualShaderNodeBillboard",
        "VisualShaderNodeDistanceFade",
        "VisualShaderNodeProximityFade",
        "VisualShaderNodeRandomRange",
        "VisualShaderNodeRemap",
        "VisualShaderNodeVarying",
        "VisualShaderNodeVaryingSetter",
        "VisualShaderNodeVaryingGetter",
        "VisualShaderNodeSDFToScreenUV",
        "VisualShaderNodeScreenUVToSDF",
        "VisualShaderNodeTextureSDF",
        "VisualShaderNodeTextureSDFNormal",
        "VisualShaderNodeSDFRaymarch",
        "VisualShaderNodeParticleOutput",
        "VisualShaderNodeParticleEmitter",
        "VisualShaderNodeParticleSphereEmitter",
        "VisualShaderNodeParticleBoxEmitter",
        "VisualShaderNodeParticleRingEmitter",
        "VisualShaderNodeParticleMeshEmitter",
        "VisualShaderNodeParticleMultiplyByAxisAngle",
        "VisualShaderNodeParticleConeVelocity",
        "VisualShaderNodeParticleRandomness",
        "VisualShaderNodeParticleAccelerator",
        "VisualShaderNodeParticleEmit",
    ]


def get_doc_path():
    return "doc_classes"


def get_icons_path():
    return "icons"
