name: Build godot-cpp
description: Build godot-cpp with the provided options.

env:
  GODOT_CPP_BRANCH: 4.3

inputs:
  bin:
    description: Path to the Godot binary.
    required: true
  scons-flags:
    description: Additional SCons flags.
    required: false
  scons-cache:
    description: The SCons cache path.
    default: ${{ github.workspace }}/godot-cpp/.scons_cache/
  scons-cache-limit:
    description: The SCons cache size limit.
    default: 1
  cache-name:
    description: The cache base name (job name by default).
    default: ${{ github.job }}

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        repository: godotengine/godot-cpp
        ref: ${{ env.GODOT_CPP_BRANCH }}
        path: godot-cpp

    - name: Extract API
      shell: sh
      run: |
        ${{ inputs.bin }} --headless --dump-gdextension-interface --dump-extension-api
        cp -f gdextension_interface.h godot-cpp/gdextension/
        cp -f extension_api.json godot-cpp/gdextension/

      # TODO: Enable caching & pass `scons-cache`/`scons-cache-limit`
      # when godot-cpp has proper cache limiting.

      # - name: Restore Godot build cache
      #   uses: ./.github/actions/godot-cache-restore
      #   with:
      #     cache-name: ${{ cache-name }}-godot-cpp
      #   continue-on-error: true

    - name: SCons Build
      shell: sh
      run: |
        echo "Building with flags: --directory=./godot-cpp/test ${{ inputs.scons-flags }}"
        scons --directory=./godot-cpp/test ${{ inputs.scons-flags }}

      # - name: Save Godot build cache
      #   uses: ./.github/actions/godot-cache-save
      #   with:
      #     cache-name: ${{ cache-name }}-godot-cpp
      #   continue-on-error: true
